services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    container_name: azurite
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=COELACANTH
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - "./tables.sql:/docker-entrypoint-initdb.d/tables.sql"
